version: "3"
services:
  mysql:
    build: server/mysql
    command: --default-authentication-plugin=mysql_native_password --secure-file-priv=""
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3307:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$DB_USERNAME --password=$$DB_PASSWORD
    volumes:
      - mysql-vol:/var/lib/mysql

  phpMyAdmin:
    depends_on:
      - mysql
    image: phpmyadmin
    restart: on-failure
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1

  q_api:
    build: server/q_api
    ports:
      - "5000:5000"

  toia-dm:
    build: server/toia-dm
    ports:
      - ${DM_PORT}:${DM_PORT}
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - ./.env

  express-api:
    depends_on:
      mysql:
        condition: service_healthy
    build:
      context: ./
      dockerfile: server/Dockerfile.dev
    restart: on-failure
    ports:
      - ${EXPRESS_PORT}:${EXPRESS_PORT}
    environment:
      - PORT=3001
      - ENVIRONMENT=development
    container_name: express-api
    volumes:
      - ./server:/app/
      - /app/node_modules
    env_file:
      - ./.env
      - ./server/.env

  react-ui:
    depends_on:
      - mysql
    build: interface
    ports:
      - "3000:3000"
    volumes:
      - ./interface:/app
      - /app/node_modules
    env_file:
      - ./.env
      - ./interface/.env

volumes:
  mysql-vol: